# Generated by Django 4.2 on 2024-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='combos', to='product.product'),
        ),
    ]
