# Generated by Django 4.2 on 2024-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_time_order',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário máximo para fazer o pedido'),
        ),
    ]
