# Generated by Django 4.2 on 2024-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_max_time_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Restaurante esta ativo'),
        ),
    ]
