# Generated by Django 4.2 on 2024-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='open_orders',
            field=models.BooleanField(default=False, verbose_name='Aberto para pedidos'),
        ),
    ]
