# Generated by Django 4.2 on 2024-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Criado em'),
        ),
    ]
